plugins {
    id 'application'
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'lib'
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
    implementation name:'bucleJuego'
}

application {
    mainClass = 'pipoo.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}
sourceSets {
    main {
        resources {
            srcDirs = ['src/main/java', 'src/main/resources']
            includes = ['**/*.png', '**/*.wav', '**/*.mp3', '**/*.properties', '**/*.ttf']
        }
    }
}