plugins {
    id 'application'
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'lib'
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
    implementation name:'bucleJuego'
}

application {
    mainClass = 'pipoo.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}
sourceSets {
    main {
        resources {
            srcDirs = ["src/main/java", "src/main/resources"]
            include "**/*.properties"
            include "**/*.wav"
            include "**/*.png"
        }
    }
}

processResources {
    from('src/main/java') {
        include '**/*.properties'
    }
    into("${buildDir}/classes/java/main")
}

jar {
    manifest {
        attributes (
                'Main-Class' : 'pipoo.core.SistemaDeJuegos'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}