#Configuracion PIPOO - Archivo: config_pong.properties
#Wed Jun 03 18:29:52 ART 2026
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
skinCancha=Original
contraBot=false
pistaMusical=Ninguna
jugador2=Jugador 2
fullScreen=false
puntosParaGanar=11
jugador1=Papa
sonidoActivado=true
teclaDownJ1=40
teclaDownJ2=83
