#Configuracion PIPOO - Archivo: config_pong.properties
#Thu Jun 04 11:01:34 ART 2026
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
skinCancha=Original
contraBot=false
pistaMusical=Ninguna
fullScreen=false
puntosParaGanar=11
sonidoActivado=true
teclaDownJ1=40
teclaDownJ2=83
nombreJ2=Jugador 2
nombreJ1=1231321
