#Configuracion PIPOO - Archivo: config_pong.properties
#Tue May 26 18:41:33 ART 2026
puntosParaGanar=11
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
pantallaCompleta=false
sonidoActivado=true
skinCancha=Original
teclaDownJ1=40
teclaDownJ2=83
pistaMusical=Pong Arcade
