#Configuracion PIPOO - Archivo: config_lode_runner.properties
#Thu Jun 04 14:54:23 ART 2026
teclaCavar=32
teclaEnter=10
pantallaCompleta=true
sonidoActivado=true
teclaEfectos=81
teclaMusica=87
pistaMusical=Remix Retro
skinPersonaje=Original
