#Configuracion PIPOO
#Thu Jun 04 11:48:22 ART 2026
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
skinCancha=Original
contraBot=false
pistaMusical=Ninguna
fullScreen=false
puntosParaGanar=11
sonidoActivado=true
teclaDownJ1=40
teclaDownJ2=83
nombreJ2=Alejo 2
nombreJ1=
