#Configuracion PIPOO - Archivo: jgame.properties
#Tue Jun 09 14:44:35 ART 2026
skinPelota=Japong
skinPaletas=Japong
teclaUpJ1=38
teclaUpJ2=87
si_teclaDisparo=32
skinCancha=Japong
si_nombreJ1=Invitado
contraBot=true
pistaMusical=Ninguna
fullScreen=false
si_fullScreen=false
si_teclaIzq=37
puntosParaGanar=11
si_skinModo=Color
sonidoActivado=true
teclaDownJ1=40
teclaDownJ2=83
si_sonidoActivado=true
si_velocidadInvasores=R\u00E1pida
nombreJ2=PIPOO BOT
si_pistaMusical=Tema 1 (Original)
si_teclaDer=39
nombreJ1=
