#Configuracion PIPOO
#Sat Jun 06 00:58:34 ART 2026
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
skinCancha=Original
contraBot=true
pistaMusical=Ninguna
fullScreen=false
puntosParaGanar=11
sonidoActivado=true
teclaDownJ1=40
teclaDownJ2=83
nombreJ2=PIPOO BOT
nombreJ1=
