#Configuracion PIPOO
#Tue Jun 02 22:32:07 ART 2026
puntosParaGanar=11
skinPelota=Original
skinPaletas=Original
teclaUpJ1=38
teclaUpJ2=87
sonidoActivado=true
skinCancha=Original
teclaDownJ1=40
teclaDownJ2=83
pistaMusical=Pong Arcade
fullScreen=false
